### ISSUE TITLE
Channels M1

### ISSUE THREAD

**Issue by moliva** [decentraland/dservices#2]
**dservices**
- [x] decentraland/dservices#7
- [x] decentraland/dservices#8

**kernel**
- [x] decentraland/kernel#324
- [ ] decentraland/kernel#325
- [x] decentraland/kernel#326
- [x] decentraland/kernel#327
- [x] decentraland/kernel#328
- [x] decentraland/kernel#329
- [x] decentraland/kernel#330
- [x] decentraland/kernel#468
- [x] decentraland/kernel#472
- [x] decentraland/kernel#518
- [ ] decentraland/kernel#519
- [ ] decentraland/kernel#520

**protocol**
- [ ] decentraland/protocol#38

**matrix-client**
- [x] decentraland/matrix-client#39
- [x] decentraland/matrix-client#40
- [x] decentraland/matrix-client#41
- [x] decentraland/matrix-client#42

**matrix-reloaded**
- [x] decentraland/matrix-reloaded#59
- [x] decentraland/matrix-reloaded#78
- [x] decentraland/matrix-reloaded#79
- [x] decentraland/matrix-reloaded#80
- [x] decentraland/matrix-reloaded#84
