### ISSUE TITLE
Chat Scalability

### ISSUE THREAD

**Issue by moliva** [decentraland/dservices#3]
**dservices**
- [ ] decentraland/dservices#9

**matrix-playbook**
- [ ] decentraland/matrix-playbook#66
- [ ] decentraland/matrix-playbook#65
- [ ] decentraland/matrix-playbook#64
- [ ] decentraland/matrix-playbook#63
- [x] decentraland/matrix-playbook#62
- [x] decentraland/matrix-playbook#61
- [x] decentraland/matrix-playbook#93
- [x] decentraland/matrix-playbook#94
- [x] decentraland/matrix-playbook#99

**matrix-reloaded**
- [ ] decentraland/matrix-reloaded#58
- [ ] decentraland/matrix-reloaded#57
- [x] decentraland/matrix-reloaded#65
- [x] decentraland/matrix-reloaded#69
- [x] decentraland/matrix-reloaded#70
- [x] decentraland/matrix-reloaded#75
