### ISSUE TITLE
[PoC] Design ADR for the user tracking and interactions within Explorer

### ISSUE THREAD

**Issue by moliva** [decentraland/dservices#36]
- [ ] Read quest tasks for user
- [x] Keep track of the current state of the player in the quest
- [x] Post new progress
- [x] Communication with SDK elements in scene and quests global scene
- [x] Potential use of a global UI scene for quests
