### ISSUE TITLE
Chat Improvements & Maintenance

### ISSUE THREAD

**Issue by moliva** [decentraland/dservices#4]
**matrix-playbook**
- [ ] decentraland/matrix-playbook#19
- [x] decentraland/matrix-playbook#21
- [x] decentraland/matrix-playbook#29
- [x] decentraland/matrix-playbook#40
- [ ] decentraland/matrix-playbook#44
- [x] decentraland/matrix-playbook#46
- [x] decentraland/matrix-playbook#48
- [x] decentraland/matrix-playbook#52
- [x] decentraland/matrix-playbook#55
- [x] decentraland/matrix-playbook#58
- [x] decentraland/matrix-playbook#60
- [x] decentraland/matrix-playbook#68
- [x] decentraland/matrix-playbook#69
- [x] decentraland/matrix-playbook#70
- [ ] decentraland/matrix-playbook#90
- [ ] decentraland/matrix-playbook#91
- [ ] decentraland/matrix-playbook#92
- [x] decentraland/matrix-playbook#93
- [x] decentraland/matrix-playbook#94
- [x] decentraland/matrix-playbook#96
- [x] decentraland/matrix-playbook#100

**matrix-reloaded**
- [ ] decentraland/matrix-reloaded#27
- [x] decentraland/matrix-reloaded#52
- [x] decentraland/matrix-reloaded#53
- [x] decentraland/matrix-reloaded#56

**matrix-client**
- [x] decentraland/matrix-client#34
- [x] decentraland/matrix-client#36
- [x] decentraland/matrix-client#37
- [x] decentraland/matrix-client#60
- [x] decentraland/matrix-client#64

**kernel**
- [x] decentraland/kernel#315
- [x] decentraland/kernel#321
- [x] decentraland/kernel#504

**kernel - friends & chat lazy loading**
- [x] decentraland/kernel#341
- [x] decentraland/kernel#342
- [x] decentraland/kernel#343
- [x] decentraland/kernel#344
- [x] decentraland/kernel#345
- [x] decentraland/kernel#389
- [x] decentraland/kernel#397
- [x] decentraland/kernel#406
- [x] decentraland/kernel#407
- [x] decentraland/kernel#411
- [x] decentraland/kernel#412
- [x] decentraland/kernel#458

**matrix-client - friends & chat lazy loading**
- [x] decentraland/matrix-client#58
