### ISSUE TITLE
[Infra] downsizing tracking issue

### ISSUE THREAD

**Issue by guidota** [decentraland/dservices#89]
## Description

Tracks downsizing of Synapse and other services:

- **Synapse**
  - EC2 Instance
    - [x] Dev: c7g.large
    - [ ] Prod: c7g.2xlarge > c7g.xlarge - [MR](https://dcl.tools/ops/matrix-deployments/-/merge_requests/51)
    
  - RDS
    - [x] Dev: db.r6g.xlarge > db.r6g.large - [MR](https://dcl.tools/ops/synapse-db/-/merge_requests/5)
    - [ ] Prod: db.r6g.xlarge > db.r6g.large
  - ElastiCache
    - [x] Dev: cache.m4.large > cache.t4g.medium - [MR](https://dcl.tools/ops/synapse-redis/-/merge_requests/6)
    - [ ] Prod: cache.m4.large > cache.t4g.medium
    
- **Quests**
  - ElastiCache
    - [x] Dev: cache.m4.large > cache.t4g.medium - [MR](https://dcl.tools/ops/quests-redis/-/merge_requests/2)
    - [x] Prod: cache.m4.large > cache.t4g.medium - [MR](https://dcl.tools/ops/quests-redis/-/merge_requests/3)

- **Social Service**
  - ElastiCache
    - [x] Dev: cache.m4.large > cache.t4g.medium - [MR](https://dcl.tools/ops/social-service-redis/-/merge_requests/4)
    - [ ] Prod: cache.m4.large > cache.t4g.medium
